name: Reusable Auto Promotion PR

on:
  workflow_call:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set target branch
        id: set_target
        run: |
          SOURCE_BRANCH=${{ github.base_ref || github.ref_name }}
          case "$SOURCE_BRANCH" in
            develop) TARGET_BRANCH="staging" ;;
            staging) TARGET_BRANCH="uat" ;;
            uat) TARGET_BRANCH="main" ;;
            *) TARGET_BRANCH="" ;;
          esac
          echo "target=$TARGET_BRANCH" >> $GITHUB_OUTPUT

      - name: Skip if no target branch
        if: steps.set_target.outputs.target == ''
        run: echo "No target branch for this merge. Skipping."

      - name: Create PR
        if: steps.set_target.outputs.target != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TARGET=${{ steps.set_target.outputs.target }}
          SOURCE=${{ github.base_ref || github.ref_name }}

          echo "Creating PR from $SOURCE → $TARGET"

          gh pr create \
            --base "$TARGET" \
            --head "$SOURCE" \
            --title "Promote $SOURCE → $TARGET" \
            --body "Automatic promotion from $SOURCE to $TARGET." \
            || echo "PR already exists or failed (might already be open)."
