name: Reusable Build & Deploy

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      image_name:
        required: true
        type: string
      env:
        required: true
        type: string
      deploy_host:
        required: true
        type: string
      deploy_user:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME: {}
      DOCKERHUB_TOKEN: {}
      SSH_PRIVATE_KEY: {}
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image tag
        id: set_tag
        run: |
          SHORT_SHA=$(git rev-parse --short=8 HEAD)
          IMAGE_TAG=${{ inputs.image_name }}:commit-${SHORT_SHA}
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.set_tag.outputs.image_tag }}

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Prepare SSH key
        id: prepare_key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
      - name: Remote deploy via SSH
        uses: appleboy/ssh-action@v0.1.11
        with:
          host: ${{ inputs.deploy_host }}
          username: ${{ inputs.deploy_user }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # ensure deploy script exists
            /usr/local/bin/deploy_service.sh "${{ inputs.service }}" "${{ inputs.env }}" "${{ needs.build_and_push.outputs.image_tag }}"
