name: Notify Ready to Review

on:
  workflow_call:
    secrets:
      READY_TO_REVIEW_DISCORD_WEBHOOK:
        required: true

jobs:
  notify_ready:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notify (Ready to Review)
        env:
          DISCORD_WEBHOOK: ${{ secrets.READY_TO_REVIEW_DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            @everyone | PR: `${{ github.event.pull_request.title }}`
            from ${{ github.event.pull_request.user.login }} is ready to review.
            ${{ github.event.pull_request.html_url }}
